version: "3.8"
services:
  db:
    container_name: postgres
    image: "postgres:13"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/edata
    environment:
      - POSTGRES_DB=todo